dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - mysql
  - postgresql
env:
  - DJANGO=2.0.13 DB=mysql
  - DJANGO=2.0.13 DB=postgres
  - DJANGO=2.1.7 DB=sqlite
  - DJANGO=2.1.7 DB=mysql
  - DJANGO=2.1.7 DB=postgres
  - DJANGO=3.0.4 DB=sqlite
  - DJANGO=3.0.4 DB=mysql
  - DJANGO=3.0.4 DB=postgres
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=3.0.4 DB=sqlite
    - python: "3.5"
      env: DJANGO=3.0.4 DB=mysql
    - python: "3.5"
      env: DJANGO=3.0.4 DB=postgres

before_script:
  - mysql -e 'create database pivot;'
  - psql -c 'create database pivot;' -U postgres
install:
  - pip install pip --upgrade
  - pip install coverage
  - pip install codecov
  - if [[ "$DB" == "mysql" && "$DJANGO" == "2.0.13" ]]; then pip install mysqlclient\<=1.3.13; fi
  - if [[ "$DB" == "mysql" && ("$DJANGO" == "2.1.7" || "$DJANGO" == "3.0.4") ]]; then pip install mysqlclient; fi
  - if [[ "$DB" == "postgres" ]]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO
script:
  - coverage run --omit="*site-packages*","*test*" runtests.py --settings=django_pivot.tests.test_"$DB"_settings
  - codecov